name: honkai_star_retail
description: Honkai Star Retail - UAP Mobile Hybrid Solution

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-SemiBold.ttf
  #         weight: 600
  # Download file Roboto terlebih dahulu
