name: honkai_star_retail
description: Honkai Star Retail - UAP Mobile Hybrid Solution

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client untuk komunikasi ke backend
  http: ^1.2.1

  # Google Sign In untuk OAuth
  google_sign_in: ^6.2.1

  # Menyimpan data lokal (token, user info)
  shared_preferences: ^2.2.3

  # Icon pack tambahan
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Rajdhani
  #     fonts:
  #       - asset: assets/fonts/Rajdhani-Regular.ttf
  #       - asset: assets/fonts/Rajdhani-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Rajdhani-SemiBold.ttf
  #         weight: 600
